language: csharp
dotnet: 2.2.401
mono: none
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
  - sudo apt-get update -y
  - sudo apt-get install python2.7 python-pip
  - sudo pip install virtualenv
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud components install cloud-datastore-emulator
before_script:
  - gcloud beta emulators datastore start --quiet --no-store-on-disk --project mappertests --host-port 0.0.0.0:8081 &
  - echo sleeping 5 seconds...
  - sleep 5
  - $(gcloud beta emulators datastore env-init)
script:
  - dotnet build --configuration Release
  - dotnet test --logger:"console;verbosity=detailed"