language: csharp
dotnet: 2.2.401
mono: none
before_install: 
  - sudo apt-get update -y
install:
  - sudo apt-get install google-cloud-sdk -y
before_script:
  - gcloud beta emulators datastore start &
  - $(gcloud beta emulators datastore env-init)
script:
  - dotnet build --configuration Release
  - dotnet test --logger:"console;verbosity=detailed"