name: ASP.NET Core CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
      
    services:
      datastore-emulator:
        image: emmekappa/google-cloud-datastore-emulator
        env:
         DATASTORE_PROJECT_ID: mappertests
         CONSISTENCY: "1.0"
         STORE_ON_DISK: "false"
        ports:
        - 8081/tcp
   
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.401
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --logger:"console;verbosity=detailed"
      env: 
        DATASTORE_EMULATOR_HOST: 127.0.0.1:${{ job.services.datastore-emulator.ports[8081] }}
        #GRPC_DNS_RESOLVER: native		
        #DATASTORE_EMULATOR_HOST: 127.0.0.1:8081
        #GRPC_VERBOSITY: INFO
        #GRPC_TRACE: call_error,health_check_client,http
